errorResetTimeout: 60000 # milliseconds
readingInterval: 60000 # milliseconds
console:
    logLevel: info
logger:
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: silly
    consoleLogging: false
    consoleLoggingLevel: silly
dhtSensor:
    fakeReading: false
    sensorType: 22
    gpioPin: 17
    minHumidityLevel: 50
humidifier:
    gpioPin: 21
dataSheet:
    credentials: /app/config/private/Humidifier Monitor-6bf015eab256.json
    spreadsheetID: 15Vc-gM_5fFdH7BFhbRnWXpgnGISO3igOSy89BsGaDyk
    sheetID: od6
    #maxRows: 43201 # +1 to account for header row
    maxRows: 10081 # +1 to account for header row
    #maxRows: 61 # +1 to account for header row
