logger:
    # error: 0
    # warn: 1
    # info: 2
    # verbose: 3
    # debug: 4
    # silly: 5
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: error
    consoleLogging: true
    consoleLoggingLevel: warn # global and app logging level
cache:
    id: cache.json
tasks:
    settings:
        lcdInterval: 250 # milliseconds
        exposure:
            max: 10000000
            min: 1000
    exposure:
        lcdInterval: 50 # milliseconds
        buzzIncrement: 50000 # uv accumulated per min
        preExposureUVReadings: 15 # counts
        maxMissingUVReadings: 10 # counts, every uvSensor.config.integrationTimeMs (about 500ms for 10 counts) will log error if xx UV readings are missed
peripherals:
    lcdScreen:
        config:
            consoleLoggingLevel: debug
            boardDebug: true
            lcdType: LCM1602
            bus:
                number: 1
                address: 0x27
    buttons:
        config:
            consoleLoggingLevel: error
            debounceMs: 500 # milliseconds
            holdDelay: 500 # milliseconds
            holdRepeat: 100 # milliseconds
        buttons:
            exposureUp:
                gpioPin: 27
            exposureDown:
                gpioPin: 22
            exposureStart:
                gpioPin: 17
            exposureStop:
                gpioPin: 4
    leds:
        config:
            consoleLoggingLevel: error
        leds:
            ledGreen:
                gpioPin: 16
            ledRed:
                gpioPin: 21
            ledYellow:
                gpioPin: 20
    buzzer:
        config:
            consoleLoggingLevel: error
            gpioPin: 26
    relays:
        config:
            consoleLoggingLevel: error
        relays:
            relayA:
                gpioPin: 14
            relayB:
                gpioPin: 15
    uvSensor:
        config:
            consoleLoggingLevel: error
            logReadingsToConsole: false
            # 50, 100, 200, 400, 800 (50ms is default)
            integrationTimeMs: 50
            bus:
                number: 1
                address: 0x10