logger:
    # error: 0
    # warn: 1
    # info: 2
    # verbose: 3
    # debug: 4
    # silly: 5
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: error
    consoleLogging: true
    # consoleLoggingLevel: info
    consoleLoggingLevel: verbose
cache:
    id: cache.json
tasks:
    settings:
        lcdInterval: 250 # milliseconds
        exposure:
            increments: 100000 # uv accumulated per min
            max: 10000000
            min: 100000
    exposure:
        lcdInterval: 500 # milliseconds
        buzzIncrement: 50000 # uv accumulated per min
        maxMissingUVReadings: 10 # will stop exposure if xx UV readings are missed
peripherals:
    lcdScreen:
        config:
            consoleLoggingLevel: debug
            lcdType: LCM1602
    giopReset:
        config:
            consoleLoggingLevel: debug
    buttons:
        config:
            consoleLoggingLevel: debug
            debounceMs: 500 # milliseconds
            holdDelay: 500 # milliseconds
            holdRepeat: 100 # milliseconds
        buttons:
            exposureUp:
                gpioPin: 27
            exposureDown:
                gpioPin: 22
            exposureStart:
                gpioPin: 17
            exposureStop:
                gpioPin: 4
    leds:
        config:
            consoleLoggingLevel: debug
        leds:
            ledGreen:
                gpioPin: 16
            ledRed:
                gpioPin: 21
            ledYellow:
                gpioPin: 20
    buzzer:
        config:
            consoleLoggingLevel: debug
            gpioPin: 26
    relays:
        config:
            consoleLoggingLevel: debug
        relays:
            relayA:
                gpioPin: 14
            relayB:
                gpioPin: 15
    uvSensor:
        config:
            consoleLoggingLevel: debug
            logReadingsToConsole: true
            # 50, 100, 200, 400, 800 (50ms is default)
            integrationTimeMs: 800
            bus:
                number: 1
                address: 0x10