logger:
    # error: 0
    # warn: 1
    # info: 2
    # verbose: 3
    # debug: 4
    # silly: 5
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: error
    consoleLogging: true
    #consoleLoggingLevel: info
    consoleLoggingLevel: silly
cache:
    id: cache.json
tasks:
    settings:
        exposure:
            increments: 1 #second
            max: 30 #seconds
            min: 0 #seconds
peripherals:
    buttons:
        config:
            debounceMs: 500 #milliseconds
        buttons:
            exposureUp:
                gpioPin: 12
            exposureDown:
                gpioPin: 6
            exposureStart:
                gpioPin: 4
            exposureStop:
                gpioPin: 18
    leds:
        config:
        leds:
            exposureOn:
                gpioPin: 17
            exposureOff:
                gpioPin: 27
            peripheralFeedback:
                gpioPin: 16
    buzzer:
        config:
            gpioPin: 5
    relays:
        config:
        relays:
            expose:
                gpioPin: 21
            idle:
                gpioPin: 20
    lcdScreen:
        config:
            i2cAddress: 0x27
    photoResistor:
        config:
            gpioPin: 26
            readIntervalMs: 100 #milliseconds