logger:
    # error: 0
    # warn: 1
    # info: 2
    # verbose: 3
    # debug: 4
    # silly: 5
    # allow individual modules to set level from method logger.getLogger()
    allowModuleOverride: false
    file: /var/log/error.log
    fileLogging: true
    fileLoggingLevel: error
    consoleLogging: true
    consoleLoggingLevel: debug
    # consoleLoggingLevel: silly
cache:
    id: cache.json
tasks:
    settings:
        lcdInterval: 1000 #milliseconds
        exposure:
            increments: 1000 #uv accumulated per min
            max: 20000
            min: 1000
    exposure:
        lcdInterval: 250 #milliseconds
peripherals:
    lcdScreen:
        config:
            consoleLoggingLevel: debug
            lcdType: LCM1602
    giopReset:
        config:
            consoleLoggingLevel: debug
    buttons:
        config:
            consoleLoggingLevel: debug
            debounceMs: 500 #milliseconds
        buttons:
            exposureUp:
                gpioPin: 12
            exposureDown:
                gpioPin: 6
            exposureStart:
                gpioPin: 4
            exposureStop:
                gpioPin: 18
    leds:
        config:
            consoleLoggingLevel: debug
        leds:
            exposureOn:
                gpioPin: 17
            exposureOff:
                gpioPin: 27
            peripheralFeedback:
                gpioPin: 16
    buzzer:
        config:
            consoleLoggingLevel: debug
            gpioPin: 5
    relays:
        config:
            consoleLoggingLevel: debug
        relays:
            expose:
                gpioPin: 21
            idle:
                gpioPin: 20
    uvSensor:
        config:
            consoleLoggingLevel: debug
            bus:
                number: 1
                address: 0x10
            readIntervalMs: 250